version: '3.9'

services:
  shell-frontend:
    build: ./shell
    ports:
      - "3000:3000"
    working_dir: /app
    restart: unless-stopped

  auth-frontend:
    build: ./auth
    ports:
      - "3001:3001"
    working_dir: /app
    restart: unless-stopped

  records-frontend:
    build: ./records
    ports:
      - "3002:3002"
    working_dir: /app
    restart: unless-stopped

  ensembles-frontend:
    build: ./ensembles
    ports:
      - "3003:3003"
    working_dir: /app
    restart: unless-stopped

  compositions-frontend:
    build: ./compositions
    ports:
      - "3004:3004"
    working_dir: /app
    restart: unless-stopped

  top-frontend:
    build: ./top
    ports:
      - "3005:3005"
    working_dir: /app
    restart: unless-stopped

  admin-frontend:
    build: ./admin
    ports:
      - "3006:3006"
    working_dir: /app
    restart: unless-stopped
