global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'records-service'
    static_configs:
      - targets: ['records-service:4002']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4001']

  - job_name: 'top-service'
    static_configs:
      - targets: ['top-service:4005']
